# Generated by Django 4.0.6 on 2022-07-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('series', models.CharField(choices=[('visa', 'mastercard')], max_length=10)),
                ('number', models.CharField(max_length=16)),
                ('release_date', models.DateTimeField()),
                ('valid_date', models.DateTimeField()),
                ('cvv_code', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('active', 'active'), ('not_active', 'not_active'), ('overdue', 'overdue')], max_length=128)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
        ),
    ]
