# Generated by Django 4.0.6 on 2022-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(default='JANIS BERZINS', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(choices=[('visa', 'visa'), ('mastercard', 'mastercard')], max_length=10),
        ),
    ]
