# Generated by Django 4.0.6 on 2022-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_history_transaction_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
