# Generated by Django 5.1.4 on 2025-01-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_card_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('release_date',)},
        ),
    ]
