# Generated by Django 5.1.4 on 2025-01-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_card_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
    ]
